export const PROFILES = {
  'israeli-progressive': {
    id: 'israeli-progressive',
    name: 'Israeli Progressive Psytrance',
    tagline: 'Progressive · Israeli school · 138–148 BPM',
    genreDescription: 'You are a progressive psytrance DJ in the Israeli school — a very specific, beautiful, coherent world. Not dark psy-techno. Not forest. Not hard trance. Progressive psytrance at its melodic, hypnotic, euphoric finest.',
    sonicDNA: 'Melodic, hypnotic, euphoric. Flowing basslines, not distorted stabs. A sound rooted in Goa trance (Astral Projection, 1996) and evolved by the Israeli scene (Captain Hook, Astrix, Liquid Soul) into a distinct art form. The dancefloor is on a collective journey, not just dancing to beats.',
    bpmHome: 143,
    bpmRange: { min: 138, max: 148 },
    bpmZones: [
      { label: 'Deep / Floating', min: 138, max: 141, role: 'Openers, float sections', artists: 'Klipsun, early Egorythmia, deep cuts', color: '#5b9bd5' },
      { label: 'Core Progressive', min: 141, max: 144, role: 'Main set body — your home', artists: 'Captain Hook, Liquid Soul, Talpa', color: '#c9a84c' },
      { label: 'Full-On Progressive', min: 144, max: 146, role: 'Build to peak', artists: 'Astrix, Vertical Mode, Ace Ventura', color: '#9b6de0' },
      { label: 'Peak Full-On', min: 146, max: 148, role: 'Explosive moments', artists: 'GMS, Astrix peaks, Vini Vici', color: '#d45b8a' },
    ],
    northStarSet: {
      title: 'Captain Hook @ Ozora 2025',
      study: 'Study this set like a film student studies Kubrick.',
      timeline: [
        { time: '00:03 – 00:36', description: 'Slow, melodic opening. Setting the hypnotic state. 33 minutes before a major energy shift.' },
        { time: '00:36 – 01:03', description: "Lost Diamond + Frankie's Wish + Arcadia — energy climbs deliberately. Each track slightly more loaded than the last." },
        { time: '01:09 – 01:33', description: 'Gravity Waves (Infected Mushroom Remix) — held for 24 unbroken minutes. The crowd surrenders completely. This is the "float" phase at maximum depth.' },
        { time: '01:33 – end', description: 'Tocando el Cielo — the emotional release. The contrast with Gravity Waves makes it hit like a freight train.' },
      ],
    },
    coreArtists: [
      { name: 'Captain Hook', sub: 'Your #1 reference' },
      { name: 'Liquid Soul', sub: 'Iboga / melodic peak' },
      { name: 'Astrix', sub: 'HOMmega / full-on' },
      { name: 'Egorythmia', sub: 'Iboga / hypnotic' },
      { name: 'Klipsun', sub: 'Deep progressive' },
      { name: 'Tijah', sub: 'Tribal, energetic' },
      { name: 'Synthatic', sub: 'Driving psy' },
      { name: 'Dekel', sub: 'Melodic / Iboga' },
      { name: 'Talpa', sub: 'Iboga / signature' },
      { name: 'Perception', sub: 'Dark progressive' },
      { name: 'Astral Projection', sub: 'Goa roots (study)' },
      { name: 'Groundbass', sub: 'Sound of Madness' },
    ],
    philosophyQuote: '"You don\'t drop in prog psy. You arrive."',
    lineage: [
      { period: '1989–1994', label: 'Goa Trance', description: "Born on the beaches of Goa, India. Exotic scales, psychedelic synths, 145+ BPM. Astral Projection's Mahadeva (1997) is your genre's direct ancestor." },
      { period: '1995–2005', label: 'Israeli Scene Emerges', description: 'Israeli producers (Infected Mushroom, Astrix, GMS) took Goa and refined it: longer builds, deeper hypnosis, sophisticated production. The "Israeli school" became the dominant global sound.' },
      { period: '2005–2015', label: 'The Iboga Era', description: 'Iboga Records defined the melodic progressive sound: Captain Hook, Liquid Soul, Egorythmia, Talpa. Emotional, flowing, euphoric. The golden age of your genre.' },
      { period: '2015–Present', label: 'Global Psytrance', description: 'Festivals like Ozora (Hungary), Boom (Portugal), Universo Paralello (Brazil) become temples. BPMs stabilise 138–146.' },
    ],
    twoSounds: {
      left: { label: 'The Iboga Sound', artists: 'Captain Hook, Liquid Soul, Egorythmia, Talpa', vibe: 'Warm, melodic, emotional journey', bpm: '138–143 BPM typical', currency: 'The "floating" currency' },
      right: { label: 'The HOMmega Sound', artists: 'Astrix, Ace Ventura, GMS', vibe: 'Harder hitting, bigger drops, festival energy', bpm: '142–148 BPM typical', currency: 'The "explosive" currency' },
    },
    keyLabels: [
      { name: 'Iboga Records', sound: 'Melodic, emotional progressive', keyArtists: 'Captain Hook, Liquid Soul, Egorythmia' },
      { name: 'HOMmega', sound: 'Full-on, driving Israeli psy', keyArtists: 'Astrix, Ace Ventura, GMS' },
      { name: 'Digital Structures', sound: 'Dark progressive, deep', keyArtists: 'Talpa, Klipsun, Blueprint' },
      { name: 'Iono Music', sound: 'Progressive psy, melodic', keyArtists: 'Egorythmia, ParanormiX' },
      { name: 'Spin Twist', sound: 'Progressive, darker edge', keyArtists: 'Sensient, Perplex' },
      { name: 'Nano Records', sound: 'UK psy, festival sound', keyArtists: 'Tristan, Laughing Buddha' },
    ],
    rekordboxBpmRange: 'set to 130–155',
    folderRoot: 'PSYTRANCE BIBLE',
    folderStructure: [
      { name: '01_FLOATING', note: '138–141 BPM, hypnotic, low energy' },
      { name: '02_PROGRESSIVE', note: '141–144 BPM, core set material' },
      { name: '03_FULL_ON_PEAK', note: '144–148 BPM, explosive moments' },
      { name: '04_TOOLS', note: 'intros, outros, tribal loops' },
      { name: '05_GOA_CLASSICS', note: 'study: Astral, early Infected' },
      { name: '06_INCOMING', note: 'new, unauditioned' },
      { name: '07_GIG_SETS/', note: 'one playlist per session' },
    ],
    libraryComposition: [
      { category: 'Floating', percentage: 25, artists: 'Klipsun, early Egorythmia', color: '#5b9bd5' },
      { category: 'Progressive', percentage: 50, artists: 'Captain Hook, Liquid Soul, Talpa', color: '#c9a84c' },
      { category: 'Full-On Peak', percentage: 15, artists: 'Astrix, GMS, Vini Vici', color: '#9b6de0' },
      { category: 'Tools', percentage: 10, artists: 'intros, outros, tribal loops', color: '#5bcfb0' },
    ],
    whereToFind: [
      { source: 'Beatport', bestFor: 'Confirmed key/BPM, large catalogue', note: 'Filter "Psytrance" — Iboga, HOMmega all there' },
      { source: 'Bandcamp', bestFor: 'Lossless FLAC, direct artist support', note: 'Search "progressive psytrance" for gems' },
      { source: 'Iboga Records shop', bestFor: 'Complete label catalogue', note: 'Your primary buying source' },
      { source: 'SoundCloud', bestFor: 'DJ mix discovery', note: 'Follow Captain Hook, Liquid Soul, Astrix' },
      { source: 'Ektoplazm', bestFor: 'Free / pay-what-you-want psy', note: 'Deep underground releases' },
    ],
    adjacentArtists: [
      { name: 'Ace Ventura', sub: 'Iboga — melodic journey' },
      { name: 'Vertical Mode', sub: 'HOMmega bridge' },
      { name: 'Sonic Species', sub: 'Slightly harder crossover' },
      { name: 'Skyfall', sub: 'Deep progressive' },
      { name: 'GMS', sub: 'Classic full-on texture' },
      { name: 'Vini Vici', sub: 'Festival peak moments' },
      { name: 'Infected Mushroom', sub: 'Classic — Gravity Waves' },
      { name: 'Parasense', sub: 'Dark progressive bridge' },
    ],
    metronomeDefaultBpm: 143,
    phrasingCaseStudy: {
      title: 'The Ozora Move (Captain Hook Pattern)',
      body: "In the Ozora 2025 set, Gravity Waves runs unbroken for 24 minutes. He wasn't sitting on his hands — he was waiting for exactly the right breakdown moment to transition to Tocando el Cielo. The patience to wait for the perfect phrase is what separates a good DJ from a great one.",
    },
  },

  'dark-forest': {
    id: 'dark-forest',
    name: 'Dark Forest Psytrance',
    tagline: 'Dark · Forest · Night Energy · 148–158 BPM',
    genreDescription: 'You are a dark forest psytrance DJ — the nocturnal soul of the psy scene. Dense, twilight-lit forests, mind-bending basslines, and an atmosphere of sacred darkness. Born from the European and Brazilian underground, it prioritises the psychedelic journey over accessible euphoria.',
    sonicDNA: 'Twisting, distorted basslines layered over sub-frequency pressure. Organic textures and alien soundscapes. The darkness is intentional and meditative — not aggressive, but liminal. Artists like Kindzadza and Orestis build entire worlds of shadow and revelation in eight-minute tracks.',
    bpmHome: 152,
    bpmRange: { min: 148, max: 158 },
    bpmZones: [
      { label: 'Dark Progressive', min: 148, max: 151, role: 'Opening, atmospheric', artists: 'Atriohm, Dark Soho', color: '#5b9bd5' },
      { label: 'Forest Core', min: 151, max: 154, role: 'Main forest body', artists: 'Kindzadza, Orestis', color: '#c9a84c' },
      { label: 'Deep Dark', min: 154, max: 156, role: 'Peak intensity', artists: 'Baphomet Engine, Menog', color: '#9b6de0' },
      { label: 'Hi-Dark', min: 156, max: 158, role: 'Twisted apex', artists: 'Derango, Tziborman', color: '#d45b8a' },
    ],
    northStarSet: {
      title: 'Kindzadza @ Ozora 2019',
      study: 'Study how the darkness builds — each track a deeper layer of the forest until escape feels impossible, then the first light arrives.',
      timeline: [
        { time: '00:00 – 00:30', description: 'Ambient intro — the forest at dusk. Subsonic pressure builds before the first kick drops.' },
        { time: '00:30 – 01:30', description: 'Twisted basslines establish the hypnotic grid. Gradual acceleration from 149 to 152 BPM.' },
        { time: '01:30 – 02:30', description: 'Peak darkness — layered distortion, alien FX, the crowd in collective altered state.' },
        { time: '02:30 – end', description: 'The first light of dawn — a softer, more melodic sequence. The contrast is devastating in the best way.' },
      ],
    },
    coreArtists: [
      { name: 'Kindzadza', sub: 'Forest master — Russian school' },
      { name: 'Orestis', sub: 'Dark progressive' },
      { name: 'Atriohm', sub: 'French dark psy' },
      { name: 'Derango', sub: 'Belgian twisted darkpsy' },
      { name: 'Dark Whisper', sub: 'Israeli dark side' },
      { name: 'Baphomet Engine', sub: 'Dark twisted' },
      { name: 'Menog', sub: 'Dark progressive / forest' },
      { name: 'Dark Soho', sub: 'Ambient dark textures' },
      { name: 'Tziborman', sub: 'Israeli forest' },
      { name: 'Loud', sub: 'South African full-dark' },
      { name: 'Fungus Funk', sub: 'Brazilian dark psy' },
      { name: 'Psykovsky', sub: 'Russian forest psychedelia' },
    ],
    philosophyQuote: '"The forest does not explain itself. Neither should your set."',
    lineage: [
      { period: '1995–2000', label: 'Dark Goa Roots', description: "The darker strands of Goa trance — Juno Reactor, Electric Universe, early Infected Mushroom — explored psychedelia beyond euphoria. The night-side of the scene was always there." },
      { period: '2000–2008', label: 'Forest Separates', description: 'European underground scenes (Germany, France, Spain) began hosting forest parties distinct from the festival mainstream. Lower BPMs, darker sound design, more emphasis on the altered state.' },
      { period: '2008–2016', label: 'Russian & Brazilian Schools', description: 'Russian producers (Kindzadza, Psykovsky) and Brazilian artists pushed the darkness further — alien soundscapes, abstract structures, 152+ BPM becoming standard in the forest.' },
      { period: '2016–Present', label: 'Global Underground', description: 'Dark psy now has a global underground network — Ektoplazm as the primary distribution, Maia Records and smaller imprints. The forest scene intentionally resists mainstream festival formats.' },
    ],
    twoSounds: {
      left: { label: 'European Forest', artists: 'Atriohm, Derango, Dark Whisper', vibe: 'Organic, layered, meditative darkness', bpm: '148–153 BPM typical', currency: 'The deep-forest currency' },
      right: { label: 'Russian / Brazilian School', artists: 'Kindzadza, Psykovsky, Fungus Funk', vibe: 'Twisted, alien, extreme psychedelia', bpm: '152–158 BPM typical', currency: 'The twisted-apex currency' },
    },
    keyLabels: [
      { name: 'Ektoplazm', sound: 'Dark, forest, twilight — free netlabel', keyArtists: 'Kindzadza, Atriohm, Fungus Funk' },
      { name: 'Maia Records', sound: 'Dark progressive to forest', keyArtists: 'Orestis, Dark Soho' },
      { name: 'Darkpsy Forest', sound: 'Pure dark/forest compilation label', keyArtists: 'Various global dark artists' },
      { name: 'Sangoma Records', sound: 'South African dark side', keyArtists: 'Loud, African Roots' },
      { name: 'Midijum Records', sound: 'French dark / forest imprint', keyArtists: 'Derango, Whiptongue' },
      { name: 'Psylife Music', sound: 'Israeli dark underground', keyArtists: 'Tziborman, Dark Whisper' },
    ],
    rekordboxBpmRange: 'set to 140–165',
    folderRoot: 'DARK FOREST',
    folderStructure: [
      { name: '01_DARK_PROGRESSIVE', note: '148–151 BPM, atmospheric, opening' },
      { name: '02_FOREST_CORE', note: '151–154 BPM, main forest body' },
      { name: '03_DEEP_DARK', note: '154–158 BPM, peak intensity' },
      { name: '04_AMBIENT_TOOLS', note: 'forest ambiences, drone intros' },
      { name: '05_CLASSICS', note: 'Kindzadza early, Psykovsky archive' },
      { name: '06_INCOMING', note: 'new, unauditioned' },
      { name: '07_GIG_SETS/', note: 'one playlist per session' },
    ],
    libraryComposition: [
      { category: 'Dark Progressive', percentage: 20, artists: 'Atriohm, Dark Soho', color: '#5b9bd5' },
      { category: 'Forest Core', percentage: 55, artists: 'Kindzadza, Orestis, Derango', color: '#c9a84c' },
      { category: 'Deep Dark Peak', percentage: 15, artists: 'Baphomet Engine, Menog', color: '#9b6de0' },
      { category: 'Ambient Tools', percentage: 10, artists: 'Forest ambience, drones', color: '#5bcfb0' },
    ],
    whereToFind: [
      { source: 'Ektoplazm', bestFor: 'Free dark/forest releases — the core archive', note: 'Your primary source — vast catalogue, quality control' },
      { source: 'Beatport', bestFor: 'Mainstream-accessible dark psy', note: 'Filter "Psychedelic Trance" → look for Maia, Sangoma' },
      { source: 'Bandcamp', bestFor: 'Direct label support, lossless audio', note: 'Search "darkpsy" and "forest psytrance"' },
      { source: 'Psyshop', bestFor: 'Physical and digital European psy', note: 'Good for obscure imprints not on Beatport' },
      { source: 'SoundCloud', bestFor: 'DJ mix discovery and free tracks', note: 'Follow Kindzadza, Orestis, Atriohm for live recordings' },
    ],
    adjacentArtists: [
      { name: 'Talamasca', sub: 'Classic dark trance crossover' },
      { name: 'Parasense', sub: 'Dark progressive bridge' },
      { name: 'Electric Universe', sub: 'Dark Goa ancestor' },
      { name: 'Xenomorph', sub: 'Cult dark forest' },
      { name: 'Dj Antagon', sub: 'Eastern European dark' },
      { name: 'Basilisk', sub: 'UK dark crossover' },
      { name: 'Ryanosaurus', sub: 'French dark forest' },
      { name: 'Cosmonet', sub: 'Alien forest textures' },
    ],
    metronomeDefaultBpm: 152,
    phrasingCaseStudy: {
      title: 'The Kindzadza Patience Principle',
      body: "In the Ozora 2019 recording, Kindzadza holds a single mid-section groove for over 20 minutes — not because he ran out of ideas, but because the altered state requires time to crystallise. In dark forest, the transition is never the point. The depth is. Rushing a dark set is the fastest way to break the spell.",
    },
  },

  'full-on': {
    id: 'full-on',
    name: 'Full-On / HOMmega School',
    tagline: 'Full-On · Festival Energy · 144–152 BPM',
    genreDescription: 'You are a full-on psytrance DJ — the festival main stage of the psy world. Driving, euphoric, and built for peak-hour moments. With roots in the Israeli HOMmega sound and Brazilian/South African crossovers, it delivers relentless energy and massive drops that command huge outdoor floors.',
    sonicDNA: 'Driving kick with heavy sub, soaring leads, and hard-hitting drops. Where Israeli progressive whispers and builds, full-on declares and delivers. Astrix, GMS, Ace Ventura — artists who know how to make 5,000 people explode simultaneously. Peak energy is the mode, not the exception.',
    bpmHome: 147,
    bpmRange: { min: 144, max: 152 },
    bpmZones: [
      { label: 'Progressive Bridge', min: 144, max: 146, role: 'Transition from prog psy', artists: 'Ace Ventura, Vertical Mode', color: '#5b9bd5' },
      { label: 'Full-On Core', min: 146, max: 149, role: 'Main floor energy', artists: 'Astrix, GMS, Neelix', color: '#c9a84c' },
      { label: 'Festival Peak', min: 149, max: 151, role: 'Maximum energy moments', artists: 'Vini Vici, Day Din', color: '#9b6de0' },
      { label: 'Hi-Octane', min: 151, max: 152, role: 'Euphoric apex', artists: 'Outsiders, Xerox', color: '#d45b8a' },
    ],
    northStarSet: {
      title: 'Astrix @ Universo Paralello 2023',
      study: 'A masterclass in sustained festival energy — how to hold a peak for 90 minutes without letting the floor breathe out.',
      timeline: [
        { time: '00:00 – 00:30', description: 'Warm entry at 144 BPM — the progressive bridge. Not yet full power. Crowd arriving.' },
        { time: '00:30 – 01:00', description: 'Acceleration to 146–147. Core HOMmega tracks. Energy locks in.' },
        { time: '01:00 – 02:00', description: 'The sustained peak — every track a weapon. The floor is locked in collective movement.' },
        { time: '02:00 – end', description: 'Final third — 149–150 BPM climax. The last 3 tracks are the ones everyone came for.' },
      ],
    },
    coreArtists: [
      { name: 'Astrix', sub: 'HOMmega — the blueprint' },
      { name: 'Ace Ventura', sub: 'Iboga/HOMmega bridge' },
      { name: 'GMS', sub: 'Classic full-on texture' },
      { name: 'Vini Vici', sub: 'Festival anthem king' },
      { name: 'Neelix', sub: 'European festival crossover' },
      { name: 'Day Din', sub: 'Israeli driving force' },
      { name: 'Outsiders', sub: 'South African full-on' },
      { name: 'Xerox & Illumination', sub: 'UK festival power' },
      { name: 'Loud', sub: 'Southern Hemisphere peak' },
      { name: 'Tristan', sub: 'UK psy full-on' },
      { name: 'Vertical Mode', sub: 'HOMmega — prog to full-on' },
      { name: 'Ticon', sub: 'Swedish full-on classic' },
    ],
    philosophyQuote: '"The peak isn\'t a reward for patience. It\'s the language of the main stage."',
    lineage: [
      { period: '1996–2002', label: 'Goa to Full Power', description: "As Goa trance matured, the Israeli scene pushed for harder, more direct energy. Infected Mushroom's Classical Mushroom (2000) redefined what a psytrance album could sound like." },
      { period: '2002–2010', label: 'HOMmega Defines the Sound', description: 'HOMmega Productions became the home of Israeli full-on: Astrix, GMS, Ace Ventura. The festival-optimised sound — built for open-air main stages, massive drops, and euphoric peaks.' },
      { period: '2010–2018', label: 'Global Full-On', description: 'South African (Outsiders, Loud), Brazilian (Vini Vici, Burn in Noise) and European (Neelix) scenes developed their own full-on dialects. The genre became truly global.' },
      { period: '2018–Present', label: 'Anthems & Crossover', description: 'Vini Vici collaborations with Armin van Buuren brought full-on to new mainstream audiences. BPMs pushed toward 150. Festival main stages from BOOM to Burning Man became the stage.' },
    ],
    twoSounds: {
      left: { label: 'Israeli HOMmega', artists: 'Astrix, GMS, Ace Ventura, Day Din', vibe: 'Tight production, groovy, melodic peaks', bpm: '145–148 BPM typical', currency: 'The precision peak' },
      right: { label: 'Global Festival', artists: 'Vini Vici, Outsiders, Neelix', vibe: 'Anthemic, massive drops, crowd-first', bpm: '148–152 BPM typical', currency: 'The stadium anthem' },
    },
    keyLabels: [
      { name: 'HOMmega Productions', sound: 'Israeli full-on, the defining label', keyArtists: 'Astrix, GMS, Day Din' },
      { name: 'Phonokol Records', sound: 'Israeli mainstream psytrance', keyArtists: 'Vini Vici, Infected Mushroom' },
      { name: 'BSR Records', sound: 'South African full-on', keyArtists: 'Outsiders, Protoculture' },
      { name: 'Loud Records', sound: 'South African driving psy', keyArtists: 'Loud, Wizzy Noise' },
      { name: 'Nano Records', sound: 'UK psytrance festival', keyArtists: 'Tristan, Laughing Buddha' },
      { name: 'Suntrip Records', sound: 'Goatrance / full-on bridge', keyArtists: 'Xerox & Illumination, U-Recken' },
    ],
    rekordboxBpmRange: 'set to 138–158',
    folderRoot: 'FULL-ON ARSENAL',
    folderStructure: [
      { name: '01_PROGRESSIVE_BRIDGE', note: '142–145 BPM, warm entry' },
      { name: '02_FULL_ON_CORE', note: '145–148 BPM, main floor energy' },
      { name: '03_FESTIVAL_PEAK', note: '148–152 BPM, maximum energy' },
      { name: '04_ANTHEMS', note: 'crowd favourites, recognisable' },
      { name: '05_CLASSICS', note: 'early HOMmega, GMS golden era' },
      { name: '06_INCOMING', note: 'new, unauditioned' },
      { name: '07_GIG_SETS/', note: 'one playlist per session' },
    ],
    libraryComposition: [
      { category: 'Progressive Bridge', percentage: 15, artists: 'Ace Ventura, Vertical Mode', color: '#5b9bd5' },
      { category: 'Full-On Core', percentage: 55, artists: 'Astrix, GMS, Day Din', color: '#c9a84c' },
      { category: 'Festival Peak', percentage: 20, artists: 'Vini Vici, Outsiders, Neelix', color: '#9b6de0' },
      { category: 'Anthems / Tools', percentage: 10, artists: 'intros, crowd anthems', color: '#5bcfb0' },
    ],
    whereToFind: [
      { source: 'Beatport', bestFor: 'Confirmed key/BPM, complete HOMmega catalogue', note: 'Filter "Psytrance" — HOMmega, Phonokol all there' },
      { source: 'Bandcamp', bestFor: 'Lossless FLAC, BSR Records direct', note: 'Search "full on psytrance" and "festival psy"' },
      { source: 'HOMmega store', bestFor: 'Official HOMmega back catalogue', note: 'Primary source for Astrix, GMS' },
      { source: 'Psyshop', bestFor: 'European full-on imports', note: 'Good for Nano Records, Suntrip, physical releases' },
      { source: 'SoundCloud', bestFor: 'Set discovery and free tracks', note: 'Follow Astrix, Vini Vici, Neelix for live recordings' },
    ],
    adjacentArtists: [
      { name: 'Burn in Noise', sub: 'Brazilian full-on' },
      { name: 'Captain Hook', sub: 'When he goes hard' },
      { name: 'Ajja', sub: 'Swiss full-on / progressive' },
      { name: 'Dekel', sub: 'Israeli prog-to-full crossover' },
      { name: 'Logic Bomb', sub: 'UK vintage full-on' },
      { name: 'Freq', sub: 'South African atmospheric' },
      { name: 'Twisted Sandstorm', sub: 'European festival' },
      { name: 'Infected Mushroom', sub: 'Later era — full power' },
    ],
    metronomeDefaultBpm: 147,
    phrasingCaseStudy: {
      title: 'The Astrix 8-Bar Principle',
      body: "In live HOMmega sets, the energy never actually drops — it just pivots. Where progressive DJs invest in long float sections, full-on DJs maintain pressure through variation. Every 8–16 bars, a textural shift keeps the floor moving without ever releasing the tension. The pause in a full-on set is 4 bars, not 24 minutes.",
    },
  },

  'melodic-techno': {
    id: 'melodic-techno',
    name: 'Melodic Techno / Organic',
    tagline: 'Melodic · Afterlife aesthetic · 128–140 BPM',
    genreDescription: 'You exist at the beautiful intersection of melodic techno and organic electronic music — the Afterlife aesthetic meets deep hypnosis. This is the sound of consciousness clubs: slower, deeper, infinitely sophisticated. Tale of Us and Anyma on one shore; Jon Hopkins and Ott on the other.',
    sonicDNA: 'Cinematic pads, minor-key melodies of devastating beauty, and hypnotic kick patterns that barely feel like techno. The tempo is deceptive — at 133 BPM the groove moves like a slow-burning dream. Every element serves the emotional arc, not the dancefloor command.',
    bpmHome: 133,
    bpmRange: { min: 128, max: 140 },
    bpmZones: [
      { label: 'Deep Organic', min: 128, max: 130, role: 'Opening, cinematic', artists: 'Jon Hopkins, Ott, ambient-adjacent', color: '#5b9bd5' },
      { label: 'Melodic Core', min: 130, max: 135, role: 'Main set body', artists: 'Tale of Us, Mathame, Innellea', color: '#c9a84c' },
      { label: 'Hypnotic Drive', min: 135, max: 138, role: 'Peak intensity', artists: 'Anyma, Massano', color: '#9b6de0' },
      { label: 'Psy Bridge', min: 138, max: 140, role: 'Crossover moments', artists: 'Bicep, Adriatique, Mind Against', color: '#d45b8a' },
    ],
    northStarSet: {
      title: 'Tale of Us @ Cercle — Notre-Dame de Paris 2018',
      study: 'The definitive statement of what melodic techno can be in an iconic space — every track chosen for emotional weight, not technical compatibility.',
      timeline: [
        { time: '00:00 – 00:40', description: 'Slow, cinematic opening. The space matters as much as the music. 45 minutes before the first real peak.' },
        { time: '00:40 – 01:10', description: 'The melodic arc builds — each track a slightly higher emotional register. The crowd surrenders to beauty, not beats.' },
        { time: '01:10 – 01:40', description: 'Harmonic peak — the most emotionally loaded tracks. The combination of space, light, and sound creates something sacred.' },
        { time: '01:40 – end', description: 'Emotional resolution. The set ends at lower energy than peak but at higher meaning. The journey is complete.' },
      ],
    },
    coreArtists: [
      { name: 'Tale of Us', sub: 'The Afterlife founders' },
      { name: 'Anyma', sub: 'Afterlife — next generation' },
      { name: 'Mathame', sub: 'Cinematic melodic techno' },
      { name: 'Innellea', sub: 'German melodic depth' },
      { name: 'Jon Hopkins', sub: 'Electronic transcendence' },
      { name: 'Massano', sub: 'Hypnotic organic techno' },
      { name: 'Adriatique', sub: 'Swiss melodic depth' },
      { name: 'Mind Against', sub: 'Afterlife — hypnotic' },
      { name: 'Bicep', sub: 'Melodic rave emotion' },
      { name: 'Shpongle', sub: 'Psychedelic ambient bridge' },
      { name: 'Ott', sub: 'Organic psychedelic depth' },
      { name: 'âme', sub: 'Classic Berlin melodic' },
    ],
    philosophyQuote: '"The most powerful emotion in electronic music is not joy or darkness — it is beauty."',
    lineage: [
      { period: '1990–2003', label: 'Detroit Roots & Berlin Adoption', description: "Techno's emotional potential was always there — Underground Resistance, Robert Hood. Berlin adopted and deepened it into something more introspective." },
      { period: '2003–2012', label: 'Organic & Minimal', description: 'The organic techno movement emerged — natural textures, longer builds, emotional depth replacing the pure machine aesthetic. Labels like Innervisions and Kompakt defined the sound.' },
      { period: '2012–2020', label: 'Afterlife Era Begins', description: 'Tale of Us founded Afterlife, synthesising dark beauty, cinematic pads, and melodic techno into a coherent global aesthetic. Cercle showcases built the scene\'s visual language.' },
      { period: '2020–Present', label: 'Global Melodic Wave', description: 'The Afterlife sound became a global phenomenon. Anyma, Massano, and the new generation push melodic techno toward full concert experiences.' },
    ],
    twoSounds: {
      left: { label: 'Afterlife Aesthetic', artists: 'Tale of Us, Anyma, Mathame, Massano', vibe: 'Dark beauty, cinematic, melodic techno', bpm: '128–135 BPM typical', currency: 'The emotional weight' },
      right: { label: 'Organic / Deep', artists: 'Jon Hopkins, Ott, Bicep, âme', vibe: 'Textural, natural, consciousness-expanding', bpm: '130–138 BPM typical', currency: 'The psychedelic depth' },
    },
    keyLabels: [
      { name: 'Afterlife', sound: 'The defining melodic techno label', keyArtists: 'Tale of Us, Anyma, Mathame' },
      { name: 'Innervisions', sound: 'Organic deep techno, Berlin', keyArtists: 'âme, Dixon, Henrik Schwarz' },
      { name: 'Kompakt', sound: 'German minimal / melodic', keyArtists: 'Various, Michael Mayer' },
      { name: 'Domino Recording', sound: 'Jon Hopkins, leftfield electronic', keyArtists: 'Jon Hopkins, Four Tet' },
      { name: 'R&S Records', sound: 'Belgian melodic crossover', keyArtists: 'Bicep, Lone' },
      { name: 'Cercle', sound: 'Curated melodic location sets', keyArtists: 'Tale of Us, Adriatique, Ben Böhmer' },
    ],
    rekordboxBpmRange: 'set to 120–145',
    folderRoot: 'MELODIC VAULT',
    folderStructure: [
      { name: '01_ORGANIC_OPEN', note: '126–130 BPM, cinematic, opening' },
      { name: '02_MELODIC_CORE', note: '130–135 BPM, emotional journey' },
      { name: '03_HYPNOTIC_DRIVE', note: '135–140 BPM, building intensity' },
      { name: '04_AMBIENT_TOOLS', note: 'transitions, ambient intros' },
      { name: '05_CLASSICS', note: 'Innervisions era, Jon Hopkins archive' },
      { name: '06_INCOMING', note: 'new, unauditioned' },
      { name: '07_GIG_SETS/', note: 'one playlist per session' },
    ],
    libraryComposition: [
      { category: 'Organic / Ambient', percentage: 20, artists: 'Jon Hopkins, Ott, âme', color: '#5b9bd5' },
      { category: 'Melodic Core', percentage: 50, artists: 'Tale of Us, Mathame, Innellea', color: '#c9a84c' },
      { category: 'Hypnotic Drive', percentage: 20, artists: 'Anyma, Massano', color: '#9b6de0' },
      { category: 'Tools', percentage: 10, artists: 'ambient transitions, drones', color: '#5bcfb0' },
    ],
    whereToFind: [
      { source: 'Beatport', bestFor: 'Melodic techno, Afterlife releases', note: 'Filter "Melodic House & Techno" — Afterlife, Innervisions' },
      { source: 'Bandcamp', bestFor: 'Jon Hopkins, independent organic artists', note: 'Search "melodic techno" and "organic techno"' },
      { source: 'Resident Advisor', bestFor: 'Reviews and label discovery', note: 'RA charts are curatorial gold for this genre' },
      { source: 'SoundCloud', bestFor: 'DJ mix discovery, Cercle sets', note: 'Follow Tale of Us, Anyma, Massano' },
      { source: 'Traxsource', bestFor: 'Deep house / melodic techno', note: 'Good for organic and minimal melodic crossovers' },
    ],
    adjacentArtists: [
      { name: 'Ben Böhmer', sub: 'German melodic progressive' },
      { name: 'Stephan Bodzin', sub: 'Modular melodic techno' },
      { name: 'Maceo Plex', sub: 'Cinematic peak energy' },
      { name: 'Nils Hoffmann', sub: 'Ethereal German melodic' },
      { name: 'Moderat', sub: 'Electronic art music crossover' },
      { name: 'Skream', sub: 'UK melodic evolution' },
      { name: 'Black Coffee', sub: 'Organic deep techno' },
      { name: 'Four Tet', sub: 'Leftfield melodic texture' },
    ],
    metronomeDefaultBpm: 133,
    phrasingCaseStudy: {
      title: 'The Tale of Us Long Game',
      body: "In the Cercle Notre-Dame recording, the first real emotional peak arrives 45 minutes into the set. Everything before it is investment. In melodic techno, more than any other electronic genre, the crowd is not waiting to dance — they're waiting to feel. Every track before the peak earns the peak. Rush it and the emotion dies.",
    },
  },

  'nitzhonot': {
    id: 'nitzhonot',
    name: 'Nitzhonot / Hi-Tech Psy',
    tagline: 'Nitzhonot · Hi-Tech · Israeli Cyber · 145–158 BPM',
    genreDescription: 'You are a Nitzhonot and hi-tech psytrance DJ — the Israeli trance tradition at its most euphoric and machine-like. Arpeggiated leads, cyber aesthetics, and relentless forward momentum. Born in Israeli clubs of the late 90s, it\'s the hardest and most distinctly "Israeli" strand of the scene.',
    sonicDNA: 'Rapid-fire arpeggios, distorted acid lines, and euphoric melodic rushes over a pounding, precise kick. The Nitzhonot aesthetic is both mechanical and ecstatic — early Infected Mushroom, Astral Projection, and the Skazi school. Where progressive psytrance builds slowly, Nitzhonot launches immediately.',
    bpmHome: 150,
    bpmRange: { min: 145, max: 158 },
    bpmZones: [
      { label: 'Progressive Entry', min: 145, max: 148, role: 'Warm up, Israeli prog bridge', artists: 'Astrix, Ace Ventura', color: '#5b9bd5' },
      { label: 'Nitzhonot Core', min: 148, max: 152, role: 'Classic Nitzhonot territory', artists: 'Astral Projection, early Infected', color: '#c9a84c' },
      { label: 'Hi-Tech Psy', min: 152, max: 155, role: 'Peak hi-tech energy', artists: 'Skazi, GMS hi-tech', color: '#9b6de0' },
      { label: 'Psyber Apex', min: 155, max: 158, role: 'Maximum machine euphoria', artists: 'Talamasca, hi-tech productions', color: '#d45b8a' },
    ],
    northStarSet: {
      title: 'Astral Projection @ Tribal Gathering 1997',
      study: 'The definitive Nitzhonot statement — where Goa roots meet Israeli machine euphoria. Every production choice influenced a decade of Israeli DJs.',
      timeline: [
        { time: '00:00 – 00:25', description: 'Cosmic intro — filtered pads, distant arpeggios. The Goa aesthetic before the machine takes over.' },
        { time: '00:25 – 01:00', description: 'Peak Nitzhonot — arpeggiated leads in full flight. The crowd in collective mechanical ecstasy.' },
        { time: '01:00 – 01:30', description: 'Melodic redemption — the "cyber sunrise" section. Euphoria over machine rhythms.' },
        { time: '01:30 – end', description: 'The Trust In Trance finale. The sound that defined Israeli psytrance for a generation.' },
      ],
    },
    coreArtists: [
      { name: 'Astral Projection', sub: 'The Nitzhonot founding fathers' },
      { name: 'Infected Mushroom', sub: 'Classical Mushroom era' },
      { name: 'GMS', sub: 'The groove formula' },
      { name: 'Skazi', sub: 'Hi-tech Nitzhonot apex' },
      { name: 'Talamasca', sub: 'French cyber psy' },
      { name: 'Protoculture', sub: 'South African Nitzhonot' },
      { name: 'Vibe Tribe', sub: 'South African cyber' },
      { name: 'Ticon', sub: 'Swedish hi-tech crossover' },
      { name: 'Son Kite', sub: 'Swedish Nitzhonot-adjacent' },
      { name: 'Man With No Name', sub: 'UK Goa / cyber ancestor' },
      { name: 'Logic Bomb', sub: 'UK hi-tech machine' },
      { name: 'Electric Universe', sub: 'German cyber euphoria' },
    ],
    philosophyQuote: '"The machine serves the ecstasy. Not the other way around."',
    lineage: [
      { period: '1993–1998', label: 'Goa to Israel', description: "Israeli producers absorbed Goa trance and pushed it harder and faster. Astral Projection's Trust in Trance (1996) defined the Israeli sound before it had a name." },
      { period: '1998–2004', label: 'Nitzhonot Crystallises', description: '"Nitzhonot" (Hebrew for "victorious") became the word for the high-energy Israeli melodic trance style. Clubs in Tel Aviv and Haifa built the scene around this specific euphoric machine-music.' },
      { period: '2004–2012', label: 'Hi-Tech Emerges', description: 'As classic Nitzhonot became "old school," the hi-tech psy movement pushed BPMs and sound design further — more twisted, more technological, inheriting the DNA but intensifying every element.' },
      { period: '2012–Present', label: 'Retro Revival & Psyber', description: 'The "psyber" aesthetic combines cyber imagery with Nitzhonot\'s core sound. Retro revival events celebrate the original era while new producers push the tradition forward.' },
    ],
    twoSounds: {
      left: { label: 'Classic Nitzhonot', artists: 'Astral Projection, early Infected Mushroom, GMS', vibe: 'Euphoric, arpeggiated, melodic machine', bpm: '145–152 BPM typical', currency: 'The cyber euphoria' },
      right: { label: 'Hi-Tech / Psyber', artists: 'Skazi, Talamasca, modern hi-tech producers', vibe: 'Harder, more twisted, machine-dominant', bpm: '152–158 BPM typical', currency: 'The apex machine rush' },
    },
    keyLabels: [
      { name: 'BNE Records', sound: 'Original Israeli Nitzhonot', keyArtists: 'Astral Projection, GMS, Infected Mushroom' },
      { name: 'Phonokol Records', sound: 'Israeli trance / Nitzhonot tradition', keyArtists: 'Vini Vici, legacy Infected Mushroom' },
      { name: 'Spiral Trax', sound: 'French cyber / hi-tech psy', keyArtists: 'Talamasca, Xenomorph' },
      { name: 'HOMmega', sound: 'Israeli evolution of the Nitzhonot core', keyArtists: 'GMS, Astrix (hi-energy side)' },
      { name: 'Plusquam Records', sound: 'German hi-tech crossover', keyArtists: 'Electric Universe, Tristan' },
      { name: 'Suntrip Records', sound: 'Goatrance / Nitzhonot bridge', keyArtists: 'Man With No Name, Yahel' },
    ],
    rekordboxBpmRange: 'set to 140–165',
    folderRoot: 'NITZHONOT VAULT',
    folderStructure: [
      { name: '01_PROG_ENTRY', note: '143–147 BPM, prog psy bridge' },
      { name: '02_NITZ_CORE', note: '148–152 BPM, classic Nitzhonot' },
      { name: '03_HI_TECH', note: '152–158 BPM, machine peak' },
      { name: '04_CLASSICS', note: 'Astral Projection archive, early Infected' },
      { name: '05_GOA_ROOTS', note: 'Goa ancestors, cyber heritage' },
      { name: '06_INCOMING', note: 'new, unauditioned' },
      { name: '07_GIG_SETS/', note: 'one playlist per session' },
    ],
    libraryComposition: [
      { category: 'Progressive Entry', percentage: 15, artists: 'Astrix, Ace Ventura', color: '#5b9bd5' },
      { category: 'Nitzhonot Core', percentage: 50, artists: 'Astral Projection, Infected, GMS', color: '#c9a84c' },
      { category: 'Hi-Tech Peak', percentage: 25, artists: 'Skazi, Talamasca', color: '#9b6de0' },
      { category: 'Goa Classics', percentage: 10, artists: 'heritage study tracks', color: '#5bcfb0' },
    ],
    whereToFind: [
      { source: 'Beatport', bestFor: 'Modern hi-tech psy, Phonokol releases', note: 'Filter "Psytrance" and search BNE, Spiral Trax' },
      { source: 'Psyshop', bestFor: 'Physical Nitzhonot releases, back catalogue', note: 'Best for BNE Records era archive' },
      { source: 'Bandcamp', bestFor: 'Independent hi-tech / psyber releases', note: 'Search "nitzhonot" and "hi-tech psytrance"' },
      { source: 'Discogs', bestFor: 'Vinyl and original CD releases of classic era', note: 'Astral Projection originals, Trust in Trance pressings' },
      { source: 'SoundCloud', bestFor: 'Retro Nitzhonot sets and new hi-tech mixes', note: 'Follow dedicated Nitzhonot channels and Israeli trance communities' },
    ],
    adjacentArtists: [
      { name: 'Yahel', sub: 'Israeli trance-to-Nitzhonot' },
      { name: 'Electric Universe', sub: 'German cyber euphoria' },
      { name: 'Space Cat', sub: 'Goa / Nitz crossover' },
      { name: 'X-Dream', sub: 'German hi-tech innovators' },
      { name: 'Hallucinogen', sub: 'UK Goa ancestor of psyber' },
      { name: 'Ra', sub: 'Israeli school classic' },
      { name: 'Juno Reactor', sub: 'Cinematic Nitzhonot-adjacent' },
      { name: 'Ticon', sub: 'Swedish hi-tech crossover' },
    ],
    metronomeDefaultBpm: 150,
    phrasingCaseStudy: {
      title: 'The Astral Projection 8-Bar Lock',
      body: "In classic Nitzhonot sets, phrase boundaries are sacred — every 8 bars is a micro-event. The arpeggio shifts, the acid line modulates, or the kick variation changes. Unlike progressive psytrance where patience is the virtue, in Nitzhonot the phrase is a promise: something changes every 8 bars. Missing a boundary breaks the machine spell.",
    },
  },
};
